### ISSUE TITLE
Lỗi khi bấm favorite

### ISSUE THREAD

**Issue by BowJaro** [TamTLeader08/FinalProject#66]
Khi tui load 2 file nhạc lên (mọi thứ bình thường) thì bấm vào home sẽ ra 2 bài history bình thường. nhưng khi chuyển qua Favorite (lúc này chưa có bài nào) thì nó vẫn hiện 2 bài của history mà không phải là bỏ trống

**Comment by BaoHaiyah** [comment]
Fixed. Thứ tự code hơi sai nên nó out function trước khi xóa display :v
