### ISSUE TITLE
Khi xóa 1 bài hát trên ổ cứng thì chương trình bị lỗi

### ISSUE THREAD

**Issue by BowJaro** [TamTLeader08/FinalProject#67]

**Comment by BowJaro** [comment]
Khi xóa 1 folder chứa nhạc cũng bị lỗi tương tự. Lỗi xảy ra khi chọn vào Home thì chương trình bị thoát

**Comment by BaoHaiyah** [comment]
cái này t chỉ sửa đc lúc mới chạy chương trình nha
còn muốn sửa thêm chỗ nào thì copy phần code check lúc chạy chương trình nhét vào chỗ đó á

**Comment by BaoHaiyah** [comment]
t sửa là nó chỉ check lúc mới chạy chương trình và nhấn home th nha
nếu đang chạy media mà xóa trong ổ cứng thì nhấn home hoặc mở lại chương trình nó mới cập nhật đc á
nếu ko thì đang chạy mà gặp bài đã xóa là nó crash á

**Comment by BowJaro** [comment]
sửa lại thành khi bấm vào 1 bài hát. check xem bài đó có tồn tại không. nếu không thì bỏ qua không phát + xóa bài đó trên giao diện + xóa trên file.txt

**Comment by BaoHaiyah** [comment]
có hàm checksong t mới tạo á
hàm đó để check rồi xóa trên file text á

**Comment by BaoHaiyah** [comment]
ông muốn khi nào check thì gọi hàm đó nha

**Comment by BowJaro** [comment]
ok. để tui thử. nhưng mà phải merge trước rồi tui mới clone về chỉnh được

**Comment by BaoHaiyah** [comment]
uk đợi approved th
tranh thủ khi nào ae hết say tết r mình làm báo cáo
